In [10]:
%pip install dotenv

Requirement already satisfied: dotenv in c:\김지은\파이썬_src\.venv\lib\site-packages (0.9.9)
Requirement already satisfied: python-dotenv in c:\김지은\파이썬_src\.venv\lib\site-packages (from dotenv) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [11]:
# 라이브러리 가져오기
import requests
import pandas as pd
import os
import dotenv

In [12]:
dotenv.load_dotenv()
my_key = os.getenv("KAKAO_RESTFULL_KEY")

In [13]:
# Kakao Map API 통해 위도, 경도 데이터 가져오는 함수를 정의
def get_geocoding(place):
    url = f"https://dapi.kakao.com/v2/local/search/address"
    headers = {"Authorization": f"KakaoAK {my_key}"}
    params = {
        'query' :place
    }
    response = requests.get(url, headers=headers,params=params)
    result = response.json()
    return result["documents"][0]["y"], result["documents"][0]["x"]

In [14]:
lat = []  #위도
lng = []  #경도

# 장소(주소) 리스트
places = ["서울특별시 종로구 세종대로 175", 
          "서울특별시 서초구 서초동 700", 
          "부산광역시 해운대구 해운대해변로 264"]

i=0
for place in places:   
    i = i + 1
    try:
        print(i, place)
        # get_geocoding 함수의 리턴값 호출하여 geo_location 변수에 저장
        place_lat, place_lon = get_geocoding(place)
        lat.append(place_lat)
        lng.append(place_lon)
        
    except:
        lat.append('')
        lng.append('')

# 데이터프레임으로 변환하기
df = pd.DataFrame({'위도':lat, '경도':lng}, index=places)

df

1 서울특별시 종로구 세종대로 175
2 서울특별시 서초구 서초동 700
3 부산광역시 해운대구 해운대해변로 264

                                     위도                경도
서울특별시 종로구 세종대로 175     37.5718478584908  126.976168275947
서울특별시 서초구 서초동 700      37.4810862955299  127.015245160054
부산광역시 해운대구 해운대해변로 264  35.1591069824231  129.160283786856

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/pia222sk20/python/main/data/sample.csv',encoding='cp949')
df.head()
df_simple = df.loc[:,['상호명','도로명주소']]
df_simple.head()

                상호명                도로명주소
0            하나산부인과   경기도 안산시 단원구 달미로 10
1          타워광명내과의원  서울특별시 강남구 언주로30길 39
2         조정현신경외과의원    경기도 시흥시 중심상가로 178
3          한귀원정신과의원    부산광역시 수영구 수영로 688
4         더블유스토어수지점   경기도 용인시 수지구 문정로 32
...             ...                  ...
91330         온누리약국      대전광역시 서구 문예로 67
91331            리원   경기도 고양시 덕양구 성신로 14
91332       참좋은요양병원    부산광역시 금정구 금강로 209
91333       경희중앙한의원    서울특별시 강동구 천중로 213
91334  천안김안과천안역본점의원  충청남도 천안시 동남구 중앙로 92

[91335 rows x 2 columns]

In [ ]:
# 위도 경고를 추가 apply
df_simple['위도경도'] = df_simple['도로명주소'].apply(lambda x : get_geocoding(x)[0])
df_simple['도로명주소'].apply(lambda x : get_geocoding(x)[1])